version: '3.8'

services:
  backend:
    image: 399827113344.dkr.ecr.ap-south-1.amazonaws.com/minijira-backend:latest
    container_name: minijira-backend
    restart: always
    env_file:
      - ./backend/.env
    expose:
      - "5000"

  frontend:
    image: 399827113344.dkr.ecr.ap-south-1.amazonaws.com/minijira-frontend:latest
    container_name: minijira-frontend
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
